### ISSUE TITLE
request offset

### ISSUE THREAD

**Issue by fann22** [Max-RM/Extend-PistonPushLimit-for-MCBE#1]
i need offset for Bedrock Dedicated Server version 1.17.40.06
please help

**Comment by fann22** [comment]
it's the linux version, not .exe

**Comment by fann22** [comment]
give me guide, how to get those offsets
i will do it on my own if i know how

**Comment by Max-RM** [comment]
> give me guide, how to get those offsets i will do it on my own if i know how

Its hard

**Comment by Max-RM** [comment]
> it's the linux version, not .exe

Tommorow

**Comment by fann22** [comment]
> > it's the linux version, not .exe
> 
> Tommorow

thank you so much

**Comment by Max-RM** [comment]
> > > it's the linux version, not .exe
> > 
> > 
> > Tommorow
> 
> thank you so much

Try this:
2C92CE1:	0C	FF
2C946F3:	0D	FF

If this will work for you, I will add it to the list.

**Comment by fann22** [comment]
> Try this: 2C92CE1: 0C FF 2C946F3: 0D FF
> 
> If this will work for you, I will add it to the list.

it worked, thank you some much

**Comment by Max-RM** [comment]
> > Try this: 2C92CE1: 0C FF 2C946F3: 0D FF
> > If this will work for you, I will add it to the list.
> 
> it worked, thank you some much

👍

**Comment by Max-RM** [comment]
> > Try this: 2C92CE1: 0C FF 2C946F3: 0D FF
> > If this will work for you, I will add it to the list.
> 
> it worked, thank you some much

Hi. Btw can I check your server? (I love tech servers)

**Comment by Max-RM** [comment]
@Fann-level-MAX
