### ISSUE TITLE
non-existing directory

### ISSUE THREAD

**Issue by NVision1st** [Max-RM/Extend-PistonPushLimit-for-MCBE#2]
![image_2024-11-06_150441542](https://github.com/user-attachments/assets/0f70ec83-9b57-4a44-bf2c-6d28ff3387cb)

when i open "EPPL_Auto_Modificator_009_universal.exe" it gives me this msg, can i fix it somehow?

**Comment by Max-RM** [comment]
Is AutoModificator exe and config file in root game directory (where minecraft exe is located)?

**Comment by NVision1st** [comment]
No, its in downloads folder. I will try that tho, thx!

**Comment by NVision1st** [comment]
(Like localappdata>packages>Microsoft.minecraftUWP>localstate>games>com.mojang)?

**Comment by NVision1st** [comment]
Ig ill just right click minecraft and go to file location

**Comment by Max-RM** [comment]
> (Like localappdata>packages>Microsoft.minecraftUWP>localstate>games>com.mojang)?

I think this is worlds and saves folder. Try to install game via MCLauncher, 
https://github.com/MCMrARM/mc-w10-version-launcher/releases/download/0.4.0/MCLauncher.zip
because you will not have access to the game folder if you will install if from Microsoft Store or Appx file.

**Comment by Max-RM** [comment]
> Ig ill just right click minecraft and go to file location

Will not work for UWP app.

**Comment by Max-RM** [comment]
@NVision1st

**Comment by NVision1st** [comment]
I alredy use the launcher (being a ssg speedrunner) so i move the exe and config to the minecraftWorlds folder or the main page (with the behavior packs folder and resorce packs folder)?

**Comment by Max-RM** [comment]
> I alredy use the launcher (being a ssg speedrunner) so i move the exe and config to the minecraftWorlds folder or the main page (with the behavior packs folder and resorce packs folder)?

To the Minecraft root game folder. I already said it above.

**Comment by NVision1st** [comment]
um it says this now 
![image_2024-11-08_164456293](https://github.com/user-attachments/assets/699f93c4-7193-4b2e-aa8e-4b11214e6bc9)

**Comment by NVision1st** [comment]
(when i try to launch game)

**Comment by NVision1st** [comment]
well i got mc to open
now it says this when i run "EPPL_Auto_Modificator_009_universal.exe"
![image_2024-11-08_170658660](https://github.com/user-attachments/assets/e3688f4b-125d-47fe-9bc0-ca3f86d27249)

**Comment by NVision1st** [comment]
heres my folder if it helps 
![image_2024-11-08_170850502](https://github.com/user-attachments/assets/50d79586-4b45-48af-8801-f087a14ce0b6)

**Comment by Max-RM** [comment]
> um it says this now ![image_2024-11-08_164456293](https://private-user-images.githubusercontent.com/172505704/384543724-699f93c4-7193-4b2e-aa8e-4b11214e6bc9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzc0NzcsIm5iZiI6MTczMTEzNzE3NywicGF0aCI6Ii8xNzI1MDU3MDQvMzg0NTQzNzI0LTY5OWY5M2M0LTcxOTMtNGIyZS1hYThlLTRiMTEyMTRlNmJjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwNzI2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iNzRjMWFlM2IwNTYyMjA4MDdhNmMwMDFiM2JhNDA0N2NhMWNlYTRjY2MyMWRhYjY1OGRkZTk4MDhhODU1YmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.VdapYNz7rjW_ANgMOlqleAb-IjHzqrUmR9-3jWy0Rvw)

You tried to run MCBE from flash drive? Why it's ExFAT, it should be NTFS.

**Comment by Max-RM** [comment]
> heres my folder if it helps ![image_2024-11-08_170850502](https://private-user-images.githubusercontent.com/172505704/384547219-50d79586-4b45-48af-8801-f087a14ce0b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzc2ODQsIm5iZiI6MTczMTEzNzM4NCwicGF0aCI6Ii8xNzI1MDU3MDQvMzg0NTQ3MjE5LTUwZDc5NTg2LTRiNDUtNDhhZi04ODAxLWYwODdhMTRjZTBiNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwNzI5NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTBiY2M1OGU3YTIxMWQwNDUwNDg1NjVkMzliMjUyZGI1YzQ3YTQyOWQ0NjUyYjY0YzA3ZjhiZGUzMDYyODliJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.E0IlpCknapdnTDK2n9Iu8DMCAwA_nq82yJkS1r_OQFY)

Can you open and show me content of "config.txt" ?

**Comment by Max-RM** [comment]
Nvm, I see that config is o kb for you. It's empty. You should paste Hex offsets into this file as it was described in the manual.

**Comment by Max-RM** [comment]
@NVision1st

**Comment by NVision1st** [comment]
Wheres the manual

**Comment by Max-RM** [comment]
> Wheres the manual

https://www.minecraftforum.net/forums/minecraft/add-ons/3194503-eppl-a-mod-to-increase-piston-push-limit-from-12

**Comment by Max-RM** [comment]
@NVision1st If you don't understand my manual then just paste this text into "consig.txt" file and save changes:
```
0x3D02091 >> 0C >> FF
0x3D02992 >> 0C >> FF
```

This text will work only for 1.21.44.01 x64 UWP (that you have rn).

**Comment by Max-RM** [comment]
Issue was closed because this problem was on user side (he didn't even read manual before starting use this mod and then started ignoring), mod still works correctly and doesn't have any REAL issues.
